apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: expense-tracker-api
  namespace: expense-tracker
spec:
  host: api.nexavend.store
  listener:
    https: https-8443
  tls:
    secret: expense-tracker-origin-tls
    redirect:
      enable: true
  upstreams:
    - name: api
      service: expense-tracker-api
      port: 80
  routes:
    - path: =/metrics
      action:
        return:
          code: 404
          type: application/json
          body: '{"detail":"Not Found"}'
    - path: =/health/live
      action:
        return:
          code: 404
          type: application/json
          body: '{"detail":"Not Found"}'
    - path: =/health/ready
      action:
        return:
          code: 404
          type: application/json
          body: '{"detail":"Not Found"}'
    - path: =/docs
      action:
        return:
          code: 404
          type: application/json
          body: '{"detail":"Not Found"}'
    - path: =/docs/oauth2-redirect
      action:
        return:
          code: 404
          type: application/json
          body: '{"detail":"Not Found"}'
    - path: =/redoc
      action:
        return:
          code: 404
          type: application/json
          body: '{"detail":"Not Found"}'
    - path: =/openapi.json
      action:
        return:
          code: 404
          type: application/json
          body: '{"detail":"Not Found"}'
    - path: /
      action:
        pass: api
