"""initial_schema

Revision ID: 2fe32207713a
Revises:
Create Date: 2026-02-27 09:45:34.801225

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2fe32207713a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "scope",
            sa.Enum("TRANSACTION", "ITEM", name="category_scope", native_enum=False),
            nullable=False,
        ),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "code", name="uq_categories_scope_code"),
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_index("ix_categories_scope_name", "categories", ["scope", "name"], unique=False)
    op.create_table(
        "merchants",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("canonical_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("country", sa.CHAR(length=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchants_canonical_name"), "merchants", ["canonical_name"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
        sa.Column("default_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("auth_provider", sa.String(length=32), nullable=False),
        sa.Column("auth_subject", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_auth_subject"), "users", ["auth_subject"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_table(
        "merchant_aliases",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("alias", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("normalized_alias", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "merchant_id",
            "user_id",
            "normalized_alias",
            name="uq_merchant_aliases_merchant_user_normalized",
        ),
    )
    op.create_index(
        op.f("ix_merchant_aliases_merchant_id"), "merchant_aliases", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_merchant_aliases_normalized_alias",
        "merchant_aliases",
        ["normalized_alias"],
        unique=False,
    )
    op.create_index("ix_merchant_aliases_user_id", "merchant_aliases", ["user_id"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_table(
        "receipts",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("storage_bucket", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("storage_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "original_filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("processing_attempt", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "UPLOADED",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="receipt_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_receipts_sha256"), "receipts", ["sha256"], unique=False)
    op.create_index(op.f("ix_receipts_uploaded_at"), "receipts", ["uploaded_at"], unique=False)
    op.create_index(op.f("ix_receipts_user_id"), "receipts", ["user_id"], unique=False)
    op.create_table(
        "user_category_overrides",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "merchant_id", name="uq_user_category_overrides_user_merchant"
        ),
    )
    op.create_index(
        op.f("ix_user_category_overrides_merchant_id"),
        "user_category_overrides",
        ["merchant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_category_overrides_user_id"),
        "user_category_overrides",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_item_category_overrides",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column("item_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "merchant_id",
            "item_key",
            name="uq_user_item_category_overrides_user_merchant_item",
        ),
    )
    op.create_index(
        op.f("ix_user_item_category_overrides_merchant_id"),
        "user_item_category_overrides",
        ["merchant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_item_category_overrides_user_id"),
        "user_item_category_overrides",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_user_item_category_overrides_user_item_global",
        "user_item_category_overrides",
        ["user_id", "item_key"],
        unique=True,
        postgresql_where=sa.text("merchant_id IS NULL"),
    )
    op.create_table(
        "receipt_extractions",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("structured_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_receipt_extractions_receipt_id"),
        "receipt_extractions",
        ["receipt_id"],
        unique=True,
    )
    op.create_table(
        "transactions",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("amount_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column("merchant_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("RECEIPT", "MANUAL", "IMPORTED", name="transaction_source", native_enum=False),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_category_id"), "transactions", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_merchant_id"), "transactions", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_occurred_at"), "transactions", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_transactions_receipt_id"), "transactions", ["receipt_id"], unique=True)
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_index(
        "ix_transactions_user_occurred_at", "transactions", ["user_id", "occurred_at"], unique=False
    )
    op.create_table(
        "transaction_items",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("qty", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount_before_discount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("is_adjustment", sa.Boolean(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("raw_line", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "transaction_id", "line_no", name="uq_transaction_items_transaction_line_no"
        ),
    )
    op.create_index(
        op.f("ix_transaction_items_category_id"), "transaction_items", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_items_transaction_id"),
        "transaction_items",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_items_transaction_id"), table_name="transaction_items")
    op.drop_index(op.f("ix_transaction_items_category_id"), table_name="transaction_items")
    op.drop_table("transaction_items")
    op.drop_index("ix_transactions_user_occurred_at", table_name="transactions")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_receipt_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_occurred_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_merchant_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_receipt_extractions_receipt_id"), table_name="receipt_extractions")
    op.drop_table("receipt_extractions")
    op.drop_index(
        "uq_user_item_category_overrides_user_item_global",
        table_name="user_item_category_overrides",
        postgresql_where=sa.text("merchant_id IS NULL"),
    )
    op.drop_index(
        op.f("ix_user_item_category_overrides_user_id"), table_name="user_item_category_overrides"
    )
    op.drop_index(
        op.f("ix_user_item_category_overrides_merchant_id"),
        table_name="user_item_category_overrides",
    )
    op.drop_table("user_item_category_overrides")
    op.drop_index(op.f("ix_user_category_overrides_user_id"), table_name="user_category_overrides")
    op.drop_index(
        op.f("ix_user_category_overrides_merchant_id"), table_name="user_category_overrides"
    )
    op.drop_table("user_category_overrides")
    op.drop_index(op.f("ix_receipts_user_id"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_uploaded_at"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_sha256"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index("ix_merchant_aliases_user_id", table_name="merchant_aliases")
    op.drop_index("ix_merchant_aliases_normalized_alias", table_name="merchant_aliases")
    op.drop_index(op.f("ix_merchant_aliases_merchant_id"), table_name="merchant_aliases")
    op.drop_table("merchant_aliases")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_auth_subject"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_merchants_canonical_name"), table_name="merchants")
    op.drop_table("merchants")
    op.drop_index("ix_categories_scope_name", table_name="categories")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
