"""add_receipt_indexes

Revision ID: 97c2cd8a8fc8
Revises: 2fe32207713a
Create Date: 2026-03-03 10:36:52.442023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c2cd8a8fc8'
down_revision: Union[str, Sequence[str], None] = '2fe32207713a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_receipts_user_id_status', 'receipts', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receipts_user_id_status', table_name='receipts')
    # ### end Alembic commands ###
