import uuid

from sqlalchemy import Column, String, UniqueConstraint
from sqlmodel import Field

from app.models.shared.timestamps import TimestampedModel


class ItemTranslation(TimestampedModel, table=True):
    """Cached per-user item text translation generated by ML Kit on clients."""

    __tablename__ = "item_translations"
    __table_args__ = (
        UniqueConstraint(
            "user_id",
            "normalized_source_text",
            "source_language",
            "target_language",
            name="uq_item_translations_user_source_lang_target",
        ),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    user_id: uuid.UUID = Field(index=True, nullable=False, foreign_key="users.id")

    source_text: str = Field(sa_column=Column(String(500), nullable=False))
    normalized_source_text: str = Field(
        sa_column=Column(String(500), nullable=False, index=True)
    )
    source_language: str = Field(sa_column=Column(String(16), nullable=False))
    target_language: str = Field(sa_column=Column(String(16), nullable=False, index=True))
    translated_text: str = Field(sa_column=Column(String(500), nullable=False))
    provider: str = Field(
        default="mlkit",
        sa_column=Column(String(32), nullable=False, default="mlkit"),
    )
