// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbRQijvgzXVFID6bwqF4kER2FYtTHoljY',
    appId: '1:897439875337:android:b9ab2a6eebca91761793d8',
    messagingSenderId: '897439875337',
    projectId: 'ai-expense-tracker-51635',
    storageBucket: 'ai-expense-tracker-51635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOVdYD8BWnyZAIOq9YwONboF3Hh_2MDnk',
    appId: '1:897439875337:ios:4a420b161f4a78441793d8',
    messagingSenderId: '897439875337',
    projectId: 'ai-expense-tracker-51635',
    storageBucket: 'ai-expense-tracker-51635.firebasestorage.app',
    androidClientId: '897439875337-qtbbnvrfps8ot7qncd2i8pbi19304gfi.apps.googleusercontent.com',
    iosClientId: '897439875337-noj8tvs63gpasg9eg3nrlrf3aorjm93i.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

}