controller:
  kind: daemonset
  hostNetwork: true
  hostPort:
    enable: true
    http: 80
    https: 8443
  containerPort:
    http: 80
    https: 8443
  service:
    create: false
  reportIngressStatus:
    enable: false
  nginxplus: false
  ingressClass:
    create: true
    name: nginx
  defaultHTTPListenerPort: 80
  defaultHTTPSListenerPort: 8443
  config:
    entries:
      real-ip-header: CF-Connecting-IP
      real-ip-recursive: "true"
      set-real-ip-from: REPLACE_WITH_TRUSTED_PROXY_CIDRS
